
#ifndef LMD_COMMANDS_AUTHS_PUBLIC_H
#define LMD_COMMANDS_AUTHS_PUBLIC_H

#include "Lmd_Commands_Public.h"

enum {
	AUTH_ADMINCHAT,
	AUTH_FULLVOTING,
	AUTH_SAVEPLACED,
	AUTH_UNFOLLOWABLE,
	AUTH_ALLOWSPEC,
	AUTH_UNIGNOREABLE,
	AUTH_CHEATS,
	AUTH_GODPROF,
	AUTH_BOTCOMMANDS,
	AUTH_BETACMDS,

	AUTH_MAX
};

typedef struct authCmdEntry_s{
	cmdEntry_t *cmd;
	int report;
	int log;
	int restr; //restrict is a gcc keyword
	int cost;
}authCmdEntry_t;

typedef struct authFile_s{
	char *name;
	char *logfile;
	int rank;
	int maxPoints;
	int flags;
	unsigned int count;
	authCmdEntry_t **entries;

	qboolean autoGenerated; //if its a numbered admin level file
}authFile_t;

#endif